# Generated by Django 4.2.5 on 2023-09-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('written_for', models.CharField(max_length=20)),
                ('written_from', models.CharField(max_length=30)),
                ('written_date', models.DateField()),
                ('monetization_status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
