# Generated by Django 4.2.5 on 2023-09-11 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='store/text_file'),
            preserve_default=False,
        ),
    ]
