# Generated by Django 4.2.5 on 2023-09-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_page',
            field=models.IntegerField(default=0),
        ),
    ]
