# Generated by Django 4.2.5 on 2023-09-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_note_note_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default=None, upload_to='user/image/'),
        ),
    ]
