# Generated by Django 4.2.5 on 2023-09-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_profile_img_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='profile_img',
            field=models.ImageField(default='user/picture/default-pic.webp', upload_to='user/picture/'),
        ),
    ]
